<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.DAL\ERP.DAL.csproj" />
    <ProjectReference Include="..\ERP.Model\ERP.Model.csproj" />
    <ProjectReference Include="..\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
